### ISSUE TITLE
Not to working with npe2 / pyproject.toml

### ISSUE THREAD

**Issue by aeisenbarth** [haesleinhuepf/napari-tools-menu#14]
The top-level `Tools` menu is created empty. Registration of items happens only when clicking them in the Plugins menu, but then the Tools menu does not update anymore.

## Example

I have a pyproject.toml containing:
```toml
[project.entry-points."napari.manifest"]
my-plugin = "my_plugin:napari.yaml"
# …
```
and Napari manifest in `my_plugin/napari.yaml`:
```yaml
name: my-plugin
display_name: My Plugin
contributions:
  commands: 
  - id: my-plugin.create_my_widget
    python_name: my_plugin:MyDock
    title: My Dock

  widgets:
  - command: my-plugin.create_my_widget
    display_name: My Dock
```
and `my_plugin/__init__.py`:
```python
from magicgui.widgets import Container
from napari_tools_menu import register_dock_widget

@register_dock_widget(menu="Oh > My Dock")
class MyDock(Container):
    ...
```

## Problems

Since the new Napari plugin engine `npe2` only reads manifests on launch of Napari, the python files are not yet read and the menus not registered (1). When triggering a command registered in the manifest, the python file is loaded and `register_dock_widget` is also called, but without effect (2).

Even if problem (2) could be solved so that the Tools menu is updated later as soon as a python file registers a new item, users would have to click the old menu first, which is not a solution.

To me it seems impossible to solve problem (1) except if there exists any plugin hook that is executed on launch.

It is also not possible to use `npe2` for Napari hooks and specify at the same time NPE1 so that Napari reads the python module and runs napari-tools-menu registration. With this extra section in pyproject.toml, Napari prefers NPE2 and ignores this:
```toml
[project.entry-points."napari.plugin"]
my-plugin = "my_plugin"
```

Reverting now completely to NPE1 is also no solution since it was deprecated and documentation mentions ["first half of 2022"](https://napari.org/stable/plugins/npe1.html).

## Solution

I think the best thing to do is to put an **info** in the top of the **readme** file saying that this project does not support `npe2`, and also roll the drum by linking [NAP6](https://napari.org/stable/naps/6-contributable-menus.html).
